### ISSUE TITLE
syslog-snmp.conf doesn't handle hostnames with dashes in them

### ISSUE THREAD

**Issue by sphilp-apc** [sexilog/sexilog#13]
Looks like the grok match in /etc/logstash/conf.d/syslog-snmp.conf should use:

`(?<hostname>[a-zA-Z0-9\-_]+[.][a-zA-Z0-9\-_\.]+|[0-9]+[\.][0-9]+[\.][0-9]+[\.][0-9]+)`

instead of:

`(?<hostname>[a-zA-Z0-9-_]+[.][a-zA-Z0-9-_\.]+|[0-9]+[\.][0-9]+[\.][0-9]+[\.][0-9]+)`

**Comment by sexilog** [comment]
"-" needs to be escaped in grok


On 25 mars 2015, at 20:15, sphilp-apc <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like the grok match in /etc/logstash/conf.d/syslog-snmp.conf should use:

(?<hostname>[a-zA-Z0-9\-_]+[.][a-zA-Z0-9\-_\.]+|[0-9]+[\.][0-9]+[\.][0-9]+[\.][0-9]+)

instead of:

(?<hostname>[a-zA-Z0-9-_]+[.][a-zA-Z0-9-_\.]+|[0-9]+[\.][0-9]+[\.][0-9]+[\.][0-9]+)
