### ISSUE TITLE
First disk 100% used

### ISSUE THREAD

**Issue by perkooo** [sexilog/sexilog#42]
Hi,

Last week, I saw the first disk going to 100% space utilisation mounted on / (was around 7 or 8GB) so I extended to 15GB.

Today I can see that it is the same...
![disk](https://cloud.githubusercontent.com/assets/17830838/18242166/3d5306e0-7355-11e6-8725-f1b1f4d3b0d4.jpg)
Any idea why ?

**Comment by vmdude** [comment]
Could you check where the space was used ?

You could run a `du -sh /*` to see what is consuming space.
I'd say it could be `/var/log`

**Comment by perkooo** [comment]
Yes, /var/log is using 13G
And 12G in /var/log/elasticsearch 

3.5G    /var/log/elasticsearch/sexilog.log.2016-09-01
5.0G    /var/log/elasticsearch/sexilog.log.2016-09-02
3.6G    /var/log/elasticsearch/sexilog.log.2016-09-03

**Comment by vmdude** [comment]
OK, so first thing to do should be to create a new file for logrotate (you can use the one from https://github.com/sexibytes/sexilog/blob/dev-elk5/etc/logrotate.d/elasticsearch)

Then this file must have a ton of error to be that big.
If you can zip it and send it to me so that I can check it.
You can delete others logs so that space will be freed

**Comment by perkooo** [comment]
Logrotate for elastisearch done.

Here the last logs (errors are the same for the largest logs also)
[sexilog.log.2016-09-04.tar.gz](https://github.com/sexibytes/sexilog/files/476763/sexilog.log.2016-09-04.tar.gz)

**Comment by vmdude** [comment]
There is a lot of errors like

`[2016-09-04 06:25:10,970][WARN ][cluster.action.shard     ] [Mach-IV] [logstash-2016.07.18][0] sending failed shard for [logstash-2016.07.18][0], node[dRzrraFCRV-iz5dTUC-OvA], [P], s[INITIALIZING], indexUUID [ni7PBDIESVWNYZ85YB6d_g], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[logstash-2016.07.18][0] failed to fetch index version after copying it over]; nested: CorruptIndexException[[logstash-2016.07.18][0] Corrupted index [corrupted_qjSKSN7xRWWyNaYgGRXZ9g] caused by: CorruptIndexException[codec header mismatch: actual header=0 vs expected header=1071082519 (resource: BufferedChecksumIndexInput(NIOFSIndexInput(path="/sexilog/sexilog/nodes/0/indices/logstash-2016.07.18/0/index/_4zl.fdx")))]]; ]]`

`[2016-09-04 06:25:10,971][WARN ][cluster.action.shard     ] [Mach-IV] [logstash-2016.07.18][0] received shard failed for [logstash-2016.07.18][0], node[dRzrraFCRV-iz5dTUC-OvA], [P], s[INITIALIZING], indexUUID [ni7PBDIESVWNYZ85YB6d_g], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[logstash-2016.07.18][0] failed to fetch index version after copying it over]; nested: CorruptIndexException[[logstash-2016.07.18][0] Corrupted index [corrupted_qjSKSN7xRWWyNaYgGRXZ9g] caused by: CorruptIndexException[codec header mismatch: actual header=0 vs expected header=1071082519 (resource: BufferedChecksumIndexInput(NIOFSIndexInput(path="/sexilog/sexilog/nodes/0/indices/logstash-2016.07.18/0/index/_4zl.fdx")))]]; ]]`

`[2016-09-04 06:25:11,018][WARN ][indices.cluster          ] [Mach-IV] [logstash-2016.07.19][0] failed to start shard`

You may need to remove corrupted indexes as these crash logstash

**Comment by perkooo** [comment]
I think I removed manually some files "logstash-2016-xx-xx" and this can be the reason why there are a lot of errors... 
This paths do not exist anymore.
Is there a solution to reset logs and start from zero ? (without re-creating VM and keeping my conf)

**Comment by vmdude** [comment]
You can check ES shards configuration with `curl sexilogIP:9200/_cat/shards`

Can you post it so that we can see their status?

**Comment by perkooo** [comment]
Here the result : 
root@shsipn-sexilog:~# curl 10.x.x.x:9200/_cat/shards
logstash-2016.09.08 0 p STARTED    34146958  25.7gb 10.x.x.x Death Adder
logstash-2016.09.09 0 p STARTED    12936249   9.8gb 10.x.x.x Death Adder
logstash-2016.09.06 0 p STARTED    32903484  25.4gb 10.x.x.x Death Adder
logstash-2016.09.07 0 p STARTED    34191263  25.7gb 10.x.x.x Death Adder
logstash-2016.09.04 0 p UNASSIGNED
logstash-2016.09.05 0 p STARTED    23577102  18.1gb 10.x.x.x Death Adder
logstash-2016.09.02 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.09.03 0 p UNASSIGNED
logstash-2016.09.16 0 p UNASSIGNED
logstash-2016.09.01 0 p UNASSIGNED
logstash-2016.08.09 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.08 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.31 0 p UNASSIGNED
logstash-2016.08.07 0 p STARTED                     10.x.x.x Death Adder
kibana-int          0 p STARTED          24 186.8kb 10.x.x.x Death Adder
logstash-2016.08.06 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.05 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.04 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.03 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.02 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.10 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.01 0 p STARTED                     10.x.x.x Death Adder
logstash-2016.08.11 0 p STARTED                     10.x.x.x Death Adder

**Comment by vmdude** [comment]
OK, have you try to restart ES service and try to execute back the query ?
It's just to be sure that they remain after service restart

**Comment by perkooo** [comment]
I restarted services, now I have this : 

_root@shsipn-sexilog:~# curl 10.x.x.x:9200/_cat/shards
logstash-2016.09.08 0 p STARTED    34146958  25.7gb 10.x.x.x Karl Lykos
logstash-2016.09.09 0 p STARTED    12936249   9.8gb 10.x.x.x Karl Lykos
logstash-2016.09.06 0 p STARTED    32903484  25.4gb 10.x.x.x Karl Lykos
logstash-2016.09.07 0 p STARTED    34191263  25.7gb 10.x.x.x Karl Lykos
logstash-2016.09.04 0 p UNASSIGNED
logstash-2016.09.05 0 p STARTED    23577102  18.1gb 10.x.x.x Karl Lykos
logstash-2016.09.16 0 p UNASSIGNED
kibana-int          0 p STARTED          24 186.8kb 10.x.x.x Karl Lykos_

My boards are not working also at the moment.

**Comment by perkooo** [comment]
Boards are working today, and elasticsearch logs are fine (~6K)

**Comment by vmdude** [comment]
Good news!
